### ISSUE TITLE
Unable to install matrix-puppet-discord: An error occurred inside the app installation script

### ISSUE THREAD

**Issue by Quiwy** [YunoHost-Apps/matrix-puppet-discord_ynh#10]
### Describe the bug

When trying to install the application, I have an error.

### Context

- Hardware: Odroid HC4
- YunoHost version: 11.0.9.15
- I have access to my server: Through SSH | through the webadmin

### Logs

https://paste.yunohost.org/raw/fohisecelo

**Comment by rosbeef** [comment]
The bug is here,

```
2022-10-06 20:18:00,351: DEBUG - npm WARN EBADENGINE   required: { node: '>=10.0.0', npm: '^6.0.0', yarn: '^1.19.0' },
2022-10-06 20:18:00,352: DEBUG - npm WARN EBADENGINE   current: { node: 'v16.17.1', npm: '8.15.0' }
```
The v before node version seems to make the problem or npm version. maybe using nvm can resolve the problem
I have the same problem.

**Comment by Quiwy** [comment]
Seems fixed with last versions

**Comment by rosbeef** [comment]
install "works" on odroid hc1 but botbridge never join the room #15

**Comment by rosbeef** [comment]
Yes works forme please close @fflorent

**Comment by fflorent** [comment]
@rosbeef Thanks for the heads-up!
