### ISSUE TITLE
Yunohost 11 - bullseye working?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/matrix-puppet-discord_ynh#6]
Could you tell me if this bridge is working under Yunogost 11 - bullseye?
I'm listing all matrix bridges available on Yunohost in here : https://github.com/YunoHost-Apps/synapse_ynh/issues/170
If it is working I'd tick it in the list.
Best regards,

**Comment by rosbeef** [comment]
i installed itb but does not work : #15

**Comment by Thatoo** [comment]
I  tick it then.
Thank you
